title: El blog de Ricardo Sol√≠s
author: ruckysolis
email: yosoy@ruckysolis.com
description: Solo probando como funciona esto

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
